### ISSUE TITLE
bug of remarkable_lib/Builder.py

### ISSUE THREAD

**Issue by frozenleaves** [jamiemcg/Remarkable#402]
in the installed file, like  
`File "/usr/lib/python3/dist-packages/remarkable_lib/Builder.py", line 92, in add_from_file
    ele_widgets = tree.getiterator("object")
AttributeError: 'ElementTree' object has no attribute 'getiterator'
`

and 
`File "/usr/lib/python3/dist-packages/remarkable_lib/Builder.py", line 115, in add_from_file
    ele_signals = tree.getiterator("signal")
AttributeError: 'ElementTree' object has no attribute 'getiterator'
`
there have a removed function ` tree.getiterator()`, if doesn't change it to `tree.iter()`, the software may cannot start

**Comment by rclUPC** [comment]
Hi. I have found a woraround with these instructions: 
https://ubuntuhandbook.org/index.php/2022/12/fix-typecatcher-ubuntu-2204/
The code should be modified in order to work with python 3.9.
